### ISSUE TITLE
Can we add timestamp for your reporting, so that every time it will be new report

### ISSUE THREAD

**Issue by automation-coe-git** [prashanth-sams/pytest-html-reporter#179]

**Comment by prashanth-sams** [comment]
@automation-coe-git good one; will add in the next iteration :)

**Comment by prashanth-sams** [comment]
@automation-coe-git The current implementation is built in a way to have archives of the previous reports. And I agree that the archives is very light-weight and high-level. I will make improvements in it rather than generating new reports with timestamp.

![image](https://user-images.githubusercontent.com/2948696/115241633-1ce2e280-a132-11eb-8078-283eb3842408.png)
